public class Main {
    public static void main(String[] args) {
        System.out.println("Задача 1");
        int v1 = 1234567890;
        byte v2 = 126;
        short v3 = 32766;
        long v4 = 2147483648L;
        float v5 = 2.566f;
        double v6 = 1.7;
        System.out.println("Значение переменной v1 с типом int равно " + v1);
        System.out.println("Значение переменной v2 с типом byte равно " + v2);
        System.out.println("Значение переменной v3 с типом short равно " + v3);
        System.out.println("Значение переменной v3 с типом long равно " + v4);
        System.out.println("Значение переменной v4 с типом float равно " + v5);
        System.out.println("Значение переменной v5 с типом double равно " + v6);
        System.out.println("Задача 2");
        int variable1 = 27897;
        byte variable2 = 67;
        short variable3 = 786;
        long variable4 = 987678965549L;
        float variable5 = 2f;
        double variable6 = 27.12;
        System.out.println("В Задаче 2, выведение результатов в консоль не требуется");
        System.out.println("Задача 3");
        byte ludmilaPavlovna = 23;
        byte annaSergeevna = 27;
        byte ekaterinaAndreevna = 30;
        short paper = 480;
        int totalstudent = ludmilaPavlovna + annaSergeevna + ekaterinaAndreevna;
        int pagePerStudent = paper / totalstudent;
        System.out.println("На каждого ученика рассчитано " + pagePerStudent + " листов бумаги");
        System.out.println("Задача 4");
        short productivity2Minute = 16;
        int productivity1Minute = productivity2Minute / 2;
        int productivity20Minute = productivity1Minute * 20;
        int productivity1Day = productivity1Minute * 60 * 24;
        int productivity3Day = productivity1Day * 3;
        int productivity1Month = productivity1Day * 30;
        System.out.println("За 20 минут работы машины, произведено бутылок " + productivity20Minute + " штук");
        System.out.println("За сутки работы машины, произведено бутылок " + productivity1Day + " штук");
        System.out.println("За 3 дня работы машины, произведено бутылок " + productivity3Day + " штук");
        System.out.println("За 1 месяц работы машины, произведено бутылок " + productivity1Month + " штук");
        System.out.println("Задача 5");
        byte totalPaint = 120;
        byte whitePaintForOneClass = 2;
        byte brownPaintForOneClass = 4;
        int totalPaintForOneClass = whitePaintForOneClass + brownPaintForOneClass;
        int totalClasses = totalPaint / totalPaintForOneClass;
        int totalWhitePaint = whitePaintForOneClass * totalClasses;
        int totalBrownPaint = brownPaintForOneClass * totalClasses;
        System.out.println("В школе, где " + totalClasses + " классов, нужно " + totalWhitePaint + " банок белой краски и " + totalBrownPaint + " банок коричневой краски");
        System.out.println("Задача 6");
        byte weightOneBanana = 80;
        byte weightMilk100Ml = 105;
        byte weightIceCreambriquette = 100;
        byte weightOneEgg = 70;
        byte quantityBanana = 5;
        byte quantityMilk = 2;
        byte quantityIceCream = 2;
        byte quantityEgg = 4;
        int totalWeightBanana = weightOneBanana * quantityBanana;
        int totalWeightMilk = weightMilk100Ml * quantityMilk;
        int totalWeightIceCream = weightIceCreambriquette * quantityIceCream;
        int totalWeightEgg = weightOneEgg * quantityEgg;
        int breakfastWeightGram = totalWeightBanana + totalWeightMilk + totalWeightIceCream + totalWeightEgg;
        System.out.println("Общий вес спорт-завтрака " + breakfastWeightGram + " грамм");
        float breakfastWeightKg = breakfastWeightGram / 1000f;
        System.out.println("Общий вес спорт-завтрака " + breakfastWeightKg + " килограмм");
        System.out.println("Задача 7");
        int goalWeight = 7;
        float option1 = (float) 250 / 1000;
        float option2 = (float) 500 /1000;
        int resultOption1 = (int) (goalWeight / option1);
        int resultOption2 = (int) (goalWeight / option2);
        System.out.println("Если спортсмен будет терять каждый день по 250 грамм, то на похудение уйдет " + resultOption1 + " дней");
        System.out.println("Если спортсмен будет терять каждый день по 500 грамм, то на похудение уйдет " + resultOption2 + " дней");
        int averageResult = (resultOption1 + resultOption2) / 2;
        System.out.println("В среднем, может потребоваться " + averageResult + " дней, чтобы добиться результата похудения");
        System.out.println("Задача 8");
        int nowPaymentMasha = 67760;
        int nowPaymentDenis = 83690;
        int nowPaymentKristina = 76230;
        float indexMonth = 0.1f;
        int newPaymentMasha = (int) (nowPaymentMasha + (nowPaymentMasha * indexMonth));
        int newPaymentDenis = (int) (nowPaymentDenis + (nowPaymentDenis * indexMonth));
        int newPaymentKristina = (int) (nowPaymentKristina + (nowPaymentKristina * indexMonth));
        int differenceMasha = (newPaymentMasha * 12) - (nowPaymentMasha * 12);
        int differenceDenis = (newPaymentDenis * 12) - (nowPaymentDenis * 12);
        int differenceKristina = (newPaymentKristina * 12) - (nowPaymentKristina * 12);
        System.out.println("Маша теперь получает " + newPaymentMasha + " рублей. Годовой доход вырос на " + differenceMasha + " рублей.");
        System.out.println("Денис теперь получает " + newPaymentDenis + " рублей. Годовой доход вырос на " + differenceDenis + " рублей.");
        System.out.println("Кристина теперь получает " + newPaymentKristina + " рублей. Годовой доход вырос на " + differenceKristina + " рублей.");

    }
}